-- SUPERSEDED by supabase/migrations/20260618100000_search_improvements.sql
-- The new migration uses a trigger-based approach that includes category names
-- in search_vector, plus adds pg_trgm fuzzy matching, search analytics, etc.
-- Do NOT run this file. Run the migration in supabase/migrations/ instead.
